### PR TITLE
Upgrade to otel@v1.23.1 and semconv/v1.24.0

### PR DESCRIPTION
**Pull request by charlieparkes-BO**
Upgrades otel and use the latest semconv schema. `otelpgx` blocks upgrading other packages because of conflicts between newer versions of semconv and `semconv/v1.17.0`.

### CODE REVIEW

**Comment by costela** [comment]
I'd suggest we wait for v1.23.0, because it will include this MR: https://github.com/open-telemetry/opentelemetry-go/pull/4876
That will hopefully make updates on different parts of the dependency chaing less of a pain :crossed_fingers:

**Comment by costela** [comment]
ok, that was fast :sweat_smile: [1.23.0 got released](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.23.0)

**Comment by charlieparkes-BO** [comment]
https://github.com/open-telemetry/opentelemetry-go/pull/4876 was a much needed change. Good call. I'll bump the version.

**Review by obitech — APPROVED** [review]
LGTM

**Comment by charlieparkes-BO** [comment]
Thank you!

**Pull request merged**
